name: Bug Report
description: Help us improve the Discord Bot by reporting bugs!
labels: 'bug'
body:
- type: textarea
  id: description
  attributes:
    label: Describe the Bug
    description: A clear description of what the bug is.
  validations:
    required: true

- type: checkboxes
  id: already-exists
  attributes:
    label: Have you checked if there is already an issue/pr for this bug?
    description: If there is already an issue/pr for this, you should participate there instead of creating a new one.
    options:
      - label: Yes, I have checked that there are no other issues or pull requests for this bug.
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ## Steps to Reproduce
      Please provide the steps to reproduce the bug:
      
- type: textarea
  id: repro-steps
  attributes:
    label: Steps to Reproduce
    description: "List the steps to reproduce the bug."
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: "What did you expect to happen?"
  validations:
    required: true

- type: textarea
  id: actual-behavior
  attributes:
    label: Actual Behavior
    description: "What actually happened?"
  validations:
    required: true

- type: input
  id: bot-version
  attributes:
    label: Bot Version
    description: "Which version of the bot are you using?"
    placeholder: e.g., v1.2.3
  validations:
    required: true

- type: input
  id: discord-channel
  attributes:
    label: Discord Channel
    description: "Provide a link to the Discord channel where the bug occurred, if applicable."
    placeholder: https://discord.com/channels/...
  validations:
    required: false

- type: textarea
  id: screenshots
  attributes:
    label: Screenshots (if applicable)
    description: "Attach any screenshots that help illustrate the problem."
    placeholder: Click in this field and then use the option *Paste, drop or click to add files*.
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: "Provide any other context about the problem here."
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      > [!TIP]
      > ### Please check again whether you have chosen a suitable title that describes/summarizes this bug report well!

