name: New Command
description: A new command that should be added to the Discord Bot.
labels: ['feature', 'suggestion']
body:
- type: textarea
  id: command-explanation
  attributes:
    label: Brief command explanation
    description: A simple explanation on what the command should do.
  validations:
    required: true

- type: checkboxes
  id: already-exists
  attributes:
    label: Have you checked if there is already an issue/pr for this feature/idea?
    description: If there is already an issue/pr for this, you should participate there instead of creating a new one.
    options:
      - label: Yes, I have checked that there are no other issues or pull requests for this feature/idea.
  validations:
    required: true

- type: textarea
  id: command-description
  attributes:
    label: Describe the command
    description: A description of the command and its parameters.
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ## Motivation
      Explain the reasoning behind this feature/idea:

- type: textarea
  id: motivation
  attributes:
    label: Motivation
    description: "Why do you think this feature/idea should be implemented? What problem does it solve or what improvement does it bring?"
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ## Notes
      Things that should be considered during the developement of the command:

- type: textarea
  id: notes
  attributes:
    label: Notes
  validations:
    required: true

- type: input
  id: examples
  attributes:
    label: Examples (if applicable)
    description: "Provide examples or mockups if applicable."
    placeholder: e.g., screenshots, code snippets, etc.
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      ## Alternatives
      Describe any alternative solutions or features you've considered:

- type: textarea
  id: alternatives
  attributes:
    label: Alternatives
    description: "Have you considered any alternative solutions or features? If so, describe them here."
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: "Provide any other context or information about the feature request."
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      > [!TIP]
      > ### Please check again whether you have chosen a suitable title that describes/summarizes this command well!
