name: Issue closed - Notify Discord
on:
  issues:
    types: [closed]
jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Post update on Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
          AUTHOR_NAME: ${{ github.event.issue.user.login }}
          AUTHOR_URL: https://github.com/${{ github.event.issue.user.login }}
          AUTHOR_ICON: https://avatars.githubusercontent.com/${{ github.event.issue.user.login }}
          TIMESTAMP: ${{ github.event.issue.closed_at }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          JSON_PAYLOAD=$(jq -n \
            --arg title "[Fertiggestellt]: $TITLE" \
            --arg description "$BODY" \
            --arg color "5763719" \
            --arg author_name "$AUTHOR_NAME" \
            --arg author_url "$AUTHOR_URL" \
            --arg author_icon "$AUTHOR_ICON" \
            --arg footer_text "Issue #$ISSUE_NUMBER" \
            --arg timestamp "$TIMESTAMP" \
            --arg username "Tanjun Issue Tracker" \
          '{
            "content": null,
            "embeds": [
              {
                "title": $title,
                "description": $description,
                "color": ($color | tonumber),
                "author": {
                  "name": $author_name,
                  "url": $author_url,
                  "icon_url": $author_icon
                },
                "footer": {
                  "text": $footer_text
                },
                "timestamp": $timestamp
              }
            ],
            "username": $username,
            "attachments": []
          }')
          curl -X POST -H 'Content-Type: application/json' -d "$JSON_PAYLOAD" "$DISCORD_WEBHOOK_URL"
