name: Ruff Lint & Format

on:
  workflow_dispatch:

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install ruff==0.11.5
      - run: ruff check .
      - run: ruff format . --check
      - run: python scripts/lint_tests.py
